version: "3"
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3308:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  server:
    build: ./server
    restart: always
    ports:
      - "8081:80"
    volumes:
      - ./server:/var/www/html
volumes:
  db_volume:


