version: "3"
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./db:/docker-entrypoint-initdb.d:ro
    ports:
      - "3308:3306"
  nginx-server:
    image: nginx
    restart: always
    volumes:
      - ./nginx-server/content:/etc/nginx/html/
      - ./nginx-server/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    links:
      - db
  apache-server:
    build: ./apache-server
    restart: always
    volumes:
      - ./apache-server/content:/var/www/html/
      - ./apache-server/000-default.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - "8081:80"
    links:
      - db
      - nginx-server
